# QR Head Configuration for Qwen3-32B

model_name_or_path: Qwen/Qwen3-32B
model_base_class: Qwen3-32B
attn_head_set: '41-14,53-37,42-3,43-10,48-25,53-35,43-18,39-37,48-30,42-4,46-27,5-7,44-33,53-55,53-51,59-26'
